wget -o 102.png https://static.wikia.nocookie.net/avatar/images/3/33/Southern_Air_Temple_outlook.png/revision/latest
wget -o 103.png https://static.wikia.nocookie.net/avatar/images/2/21/Suki_and_Sokka_train.png/revision/latest
wget -o 104.png https://static.wikia.nocookie.net/avatar/images/e/e8/King_Bumi.png/revision/latest
wget -o 105.png https://static.wikia.nocookie.net/avatar/images/6/65/Katara_speeches.png/revision/latest
wget -o 106.png https://static.wikia.nocookie.net/avatar/images/0/0b/Hei_Bai.png/revision/latest
wget -o 107.png https://static.wikia.nocookie.net/avatar/images/c/c0/Aang_meets_Roku.png/revision/latest
wget -o 108.png https://static.wikia.nocookie.net/avatar/images/3/3b/Waterbending_scroll.png/revision/latest
wget -o 109.png https://static.wikia.nocookie.net/avatar/images/5/59/Jet_shows_his_true_colors.png/revision/latest
wget -o 110.png https://static.wikia.nocookie.net/avatar/images/d/df/Gan_Jin_vs._Zhang.png/revision/latest
wget -o 111.png https://static.wikia.nocookie.net/avatar/images/2/22/Giant_wave.png/revision/latest
wget -o 112.png https://static.wikia.nocookie.net/avatar/images/f/f9/Aang_rescued_by_the_Blue_Spirit.png/revision/latest
wget -o 113.png https://static.wikia.nocookie.net/avatar/images/d/dc/Aunt_Wu_reads_the_clouds.png/revision/latest
wget -o 114.png https://static.wikia.nocookie.net/avatar/images/a/a3/Katara%2C_Sokka%2C_and_Bato_hug.png/revision/latest
wget -o 115.png https://static.wikia.nocookie.net/avatar/images/a/aa/Jeong_Jeong_meditating.png/revision/latest
wget -o 116.png https://static.wikia.nocookie.net/avatar/images/2/2d/Northern_Air_Temple.png/revision/latest
wget -o 117.png https://static.wikia.nocookie.net/avatar/images/d/da/Pakku_waterbends.png/revision/latest
wget -o 118.png https://static.wikia.nocookie.net/avatar/images/e/e2/Black_snow_clouds.png/revision/latest
wget -o 119.png https://static.wikia.nocookie.net/avatar/images/9/9a/Koizilla_destroys_the_Navy.png/revision/latest